### PR TITLE
New Ships

### PR DESCRIPTION
**Pull request by CrazyVulcan**
Xi Shuttle
LAAT Transport
HMP Gunship

### CODE REVIEW

**Comment by CrazyVulcan** [comment]
Hello thought I would lend a hand as I did the images for TTS and stuff already, later

**Comment by sirjorj** [comment]
Thank you!

**Comment by sirjorj** [comment]
font file looks good - it is up and running here https://xhud.sirjorj.com/xwing.cgi/pilots2

**Comment by AlexRaubach** [comment]
Thanks for the hard work, I've also deployed this version to metawing2 with zero issues.

**Comment by geordanr** [comment]
Thanks!

What are the codepoints for the new icons?  I'll update the CSS and list of icons.

**Comment by geordanr** [comment]
Whoops I didn't see they were already updated, thanks!

**Pull request merged**
