### PR TITLE
Add missing TIE Fighter class

### PR DESCRIPTION
**Pull request by guidokessels**
I noticed this was missing :)

### CODE REVIEW

**Comment by geordanr** [comment]
Thanks!

**Comment by guidokessels** [comment]
No problem!

Do you mind if I use the font in my app? It's so much nicer than the images I'm using.

**Comment by geordanr** [comment]
I don't mind -- that's why I made this package, so that the font can be easily used!

I'm about to update it with the energy icon from @armoredgear7, should be up soon.

**Comment by guidokessels** [comment]
Awesome, thanks.

**Pull request merged**
