### PR TITLE
npm tests

### PR DESCRIPTION
**Pull request by mludowise**
Added some tests that…
  - Verify every icon specified in the icon-map has a valid glyph in the corresponding font TTF file.
  - Verify that ship names are consistent with the xwing-data repo.
  - Warn if missing any ship icons that correspond to ships in xwing-data.

Note that this PR is dependent on #44 because it requires JSON map files and will need a rebase before it can be merged.

### CODE REVIEW

**Comment by geordanr** [comment]
Will review once conflicts are resolved.

**Comment by mludowise** [comment]
Conflicts should be resolved now.

**Comment by geordanr** [comment]
Cool.  I've set up Travis to build and test on commits, so now future pull requests should get automatically tested.  Thanks!

**Comment by mludowise** [comment]
Awesome!

**Pull request merged**
